spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "152956967648-0uksl64kpstokcucj62slbbv0gp1gv5m.apps.googleusercontent.com"
            client-secret: "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"
            redirectUri: "http://localhost:8080/oauth2/callback/google"
            scope: profile, email
app:
  auth:
    token:
      secret-key: "6B64DCA4E72F58EDIKU9AAB215FE7"
      refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUri: "http://localhost:3000/oauth2/redirect"
#app:
#  auth:
#    token:
#      secret-key: "WhiJuOCW98RIzwRCyoE0aWSRmPexDeV2"
#      refresh-cookie-key: "refresh"
#  oauth2:
#    authorizedRedirectUri: "http://localhost:8080/login/oauth2/code/kakao"